context:
  version: 2024.05.08

package:
  name: khronos-opencl-icd-loader
  version: ${{ version }}

source:
  - url: https://github.com/KhronosGroup/OpenCL-ICD-Loader/archive/refs/tags/v${{ version }}.zip
    sha256: 3326b81cd47829a8b738465944674e94332b55d988e12bbb760f54d71a0ac9a6
    patches:
      - no_check_integrity_win.patch
  - url: https://github.com/KhronosGroup/OpenCL-Headers/archive/v${{ version }}.zip
    sha256: 83296f08e670d8f52c94972587f22ad8cbbb1383aa00b11f376a9c01686bf399
    target_directory: inc

build:
  number: 0
  # We've got ocl-icd on Linux which has better debugging support
  # and was used before khronos adopted an open source license.
  # new versions don't support older MSVC

  # I actually need to build this on Linux
  skip:
    - win and vc<14

requirements:
  build:
    - cmake
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - python
    - if: not win
      then: make
    - if: win
      then: ninja
  host:
  run:
  run_exports:
    - ${{ pin_subpackage("khronos-opencl-icd-loader", upper_bound=None) }}

tests:
  - downstream: pyopencl
  - script:
      - if: win
        then: if not exist %LIBRARY_INC%\\CL\\cl.h exit 1
      - if: win
        then: if not exist %LIBRARY_BIN%\\OpenCL.dll exit 1
      - if: osx
        then: test -f $PREFIX/include/OpenCL/cl.h
      - if: linux
        then: test -f $PREFIX/include/CL/cl.h
      - if: unix
        then: test -f $PREFIX/lib/libOpenCL${SHLIB_EXT}

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A driver loader for OpenCL
  homepage: https://www.khronos.org/registry/cl/
  repository: https://github.com/KhronosGroup/OpenCL-ICD-Loader

extra:
  recipe-maintainers:
    - inducer
    - isuruf

